# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sophiapeaslee/Desktop/Programs/game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sophiapeaslee/Desktop/Programs/game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sophiapeaslee/Desktop/Programs/game/CMakeFiles /Users/sophiapeaslee/Desktop/Programs/game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sophiapeaslee/Desktop/Programs/game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named citybuilder

# Build rule for target.
citybuilder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 citybuilder
.PHONY : citybuilder

# fast build rule for target.
citybuilder/fast:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/build
.PHONY : citybuilder/fast

animation_handler.o: animation_handler.cpp.o

.PHONY : animation_handler.o

# target to build an object file
animation_handler.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/animation_handler.cpp.o
.PHONY : animation_handler.cpp.o

animation_handler.i: animation_handler.cpp.i

.PHONY : animation_handler.i

# target to preprocess a source file
animation_handler.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/animation_handler.cpp.i
.PHONY : animation_handler.cpp.i

animation_handler.s: animation_handler.cpp.s

.PHONY : animation_handler.s

# target to generate assembly for a file
animation_handler.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/animation_handler.cpp.s
.PHONY : animation_handler.cpp.s

city.o: city.cpp.o

.PHONY : city.o

# target to build an object file
city.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/city.cpp.o
.PHONY : city.cpp.o

city.i: city.cpp.i

.PHONY : city.i

# target to preprocess a source file
city.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/city.cpp.i
.PHONY : city.cpp.i

city.s: city.cpp.s

.PHONY : city.s

# target to generate assembly for a file
city.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/city.cpp.s
.PHONY : city.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game.cpp.s
.PHONY : game.cpp.s

game_state_editor.o: game_state_editor.cpp.o

.PHONY : game_state_editor.o

# target to build an object file
game_state_editor.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game_state_editor.cpp.o
.PHONY : game_state_editor.cpp.o

game_state_editor.i: game_state_editor.cpp.i

.PHONY : game_state_editor.i

# target to preprocess a source file
game_state_editor.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game_state_editor.cpp.i
.PHONY : game_state_editor.cpp.i

game_state_editor.s: game_state_editor.cpp.s

.PHONY : game_state_editor.s

# target to generate assembly for a file
game_state_editor.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game_state_editor.cpp.s
.PHONY : game_state_editor.cpp.s

game_state_start.o: game_state_start.cpp.o

.PHONY : game_state_start.o

# target to build an object file
game_state_start.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game_state_start.cpp.o
.PHONY : game_state_start.cpp.o

game_state_start.i: game_state_start.cpp.i

.PHONY : game_state_start.i

# target to preprocess a source file
game_state_start.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game_state_start.cpp.i
.PHONY : game_state_start.cpp.i

game_state_start.s: game_state_start.cpp.s

.PHONY : game_state_start.s

# target to generate assembly for a file
game_state_start.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/game_state_start.cpp.s
.PHONY : game_state_start.cpp.s

gui.o: gui.cpp.o

.PHONY : gui.o

# target to build an object file
gui.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/gui.cpp.o
.PHONY : gui.cpp.o

gui.i: gui.cpp.i

.PHONY : gui.i

# target to preprocess a source file
gui.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/gui.cpp.i
.PHONY : gui.cpp.i

gui.s: gui.cpp.s

.PHONY : gui.s

# target to generate assembly for a file
gui.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/gui.cpp.s
.PHONY : gui.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/main.cpp.s
.PHONY : main.cpp.s

map.o: map.cpp.o

.PHONY : map.o

# target to build an object file
map.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/map.cpp.o
.PHONY : map.cpp.o

map.i: map.cpp.i

.PHONY : map.i

# target to preprocess a source file
map.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/map.cpp.i
.PHONY : map.cpp.i

map.s: map.cpp.s

.PHONY : map.s

# target to generate assembly for a file
map.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/map.cpp.s
.PHONY : map.cpp.s

texture_manager.o: texture_manager.cpp.o

.PHONY : texture_manager.o

# target to build an object file
texture_manager.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/texture_manager.cpp.o
.PHONY : texture_manager.cpp.o

texture_manager.i: texture_manager.cpp.i

.PHONY : texture_manager.i

# target to preprocess a source file
texture_manager.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/texture_manager.cpp.i
.PHONY : texture_manager.cpp.i

texture_manager.s: texture_manager.cpp.s

.PHONY : texture_manager.s

# target to generate assembly for a file
texture_manager.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/texture_manager.cpp.s
.PHONY : texture_manager.cpp.s

tile.o: tile.cpp.o

.PHONY : tile.o

# target to build an object file
tile.cpp.o:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/tile.cpp.o
.PHONY : tile.cpp.o

tile.i: tile.cpp.i

.PHONY : tile.i

# target to preprocess a source file
tile.cpp.i:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/tile.cpp.i
.PHONY : tile.cpp.i

tile.s: tile.cpp.s

.PHONY : tile.s

# target to generate assembly for a file
tile.cpp.s:
	$(MAKE) -f CMakeFiles/citybuilder.dir/build.make CMakeFiles/citybuilder.dir/tile.cpp.s
.PHONY : tile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... citybuilder"
	@echo "... animation_handler.o"
	@echo "... animation_handler.i"
	@echo "... animation_handler.s"
	@echo "... city.o"
	@echo "... city.i"
	@echo "... city.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... game_state_editor.o"
	@echo "... game_state_editor.i"
	@echo "... game_state_editor.s"
	@echo "... game_state_start.o"
	@echo "... game_state_start.i"
	@echo "... game_state_start.s"
	@echo "... gui.o"
	@echo "... gui.i"
	@echo "... gui.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map.o"
	@echo "... map.i"
	@echo "... map.s"
	@echo "... texture_manager.o"
	@echo "... texture_manager.i"
	@echo "... texture_manager.s"
	@echo "... tile.o"
	@echo "... tile.i"
	@echo "... tile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

